# Temp for sturdy env
- name: Overwrite dns issues
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
- name: Overwrite yum settings
  template:
    src: yum.conf
    dest: /etc/yum.conf

- name: Install supporting packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: [ruby, mongodb-server, mongodb, nano]

- name: friendly name of editor
  file:
    src: /bin/nano
    dest: /bin/pico
    state: link

- name: Install gems
  gem:
    name: "{{ item }}"
    state: latest
    user_install: no
  with_items: [aws-sdk]

- name: start mongodb server
  service:
    name: mongod
    enabled: true
    state: started

# - name: Pip install pymongo
#   pip:
#     name: pymongo
#
# - name: Admin user for mongo
#   mongodb_user:
#     database: admin
#     name: mongo-admin
#     # password: {{ lookup('sis-ssm', '/site/pluto/mongo/admin-user') }}
#     password: 12345
#     state: present

- name: configure mongodb-server
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  notify:
    - restart mongod

- meta: flush_handlers

- name: Register IP with R53 and get mongo servers
  action: ec2_mongo hosted_zone_id={{ hosted_zone_id }} assume_role_arn={{ assume_role_arn }}
  register: mongo_struct
