- name: Install supporting packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: [ruby, ruby-devel, gcc, mongodb-server, mongodb]

- name: Install gems
  gem:
    name: "{{ item }}"
    state: latest
  with_items: [aws-sdk, mongo]

- name: Pip install pymongo
  pip:
    name: pymongo

- name: start mongodb server
  service:
    name: mongod
    enabled: true
    state: started

# - name: Admin user for mongo
#   mongodb_user:
#     database: admin
#     name: mongo-admin
#     # password: {{ lookup('sis-ssm', '/site/pluto/mongo/admin-user') }}
#     password: 12345
#     state: present

- name: configure mongodb-server
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  notify:
    - restart mongod

- name: Register IP with R53 and get mongo servers
  action: ec2_mongo hosted_zone_id={{ hosted_zone_id }} assume_role_arn={{ assume_role_arn }}
  register: mongo_struct
